"""add fee payments

Revision ID: 26ee46e11efe
Revises: c15631020caf
Create Date: 2026-09-09 15:18:43.592148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26ee46e11efe'
down_revision: Union[str, Sequence[str], None] = 'c15631020caf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fee_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fee_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=False),
    sa.Column('payment_method', sa.String(length=30), nullable=False),
    sa.Column('transaction_reference', sa.String(length=100), nullable=True),
    sa.Column('receipt_number', sa.String(length=50), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fee_id'], ['fees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fee_payments_fee_id'), 'fee_payments', ['fee_id'], unique=False)
    op.create_index(op.f('ix_fee_payments_receipt_number'), 'fee_payments', ['receipt_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fee_payments_receipt_number'), table_name='fee_payments')
    op.drop_index(op.f('ix_fee_payments_fee_id'), table_name='fee_payments')
    op.drop_table('fee_payments')
    # ### end Alembic commands ###
