"""Add student link to admission applications

Revision ID: 33597abb003b
Revises: aba9c2965732
Create Date: 2026-09-08 22:37:19.464164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33597abb003b'
down_revision: Union[str, Sequence[str], None] = 'aba9c2965732'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admission_applications', sa.Column('student_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'admission_applications', ['student_id'])
    op.create_foreign_key(None, 'admission_applications', 'students', ['student_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'admission_applications', type_='foreignkey')
    op.drop_constraint(None, 'admission_applications', type_='unique')
    op.drop_column('admission_applications', 'student_id')
    # ### end Alembic commands ###
