"""enhance parent child relationships

Revision ID: 69985b559509
Revises: 16403ad69bf4
Create Date: 2026-09-08 21:25:49.807461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69985b559509'
down_revision: Union[str, Sequence[str], None] = '16403ad69bf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parent_children', sa.Column('relation_type', sa.String(length=30), nullable=False))
    op.add_column('parent_children', sa.Column('is_primary', sa.Boolean(), nullable=False))
    op.add_column('parent_children', sa.Column('is_emergency_contact', sa.Boolean(), nullable=False))
    op.add_column('parent_children', sa.Column('receives_notifications', sa.Boolean(), nullable=False))
    op.add_column('parent_children', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('parent_children', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parent_children', 'updated_at')
    op.drop_column('parent_children', 'created_at')
    op.drop_column('parent_children', 'receives_notifications')
    op.drop_column('parent_children', 'is_emergency_contact')
    op.drop_column('parent_children', 'is_primary')
    op.drop_column('parent_children', 'relation_type')
    # ### end Alembic commands ###
