"""add unique constraint to attendance

Revision ID: 72dc4bd8a3a0
Revises: a9d672dcd0f6
Create Date: 2026-09-07 18:57:20.520873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72dc4bd8a3a0'
down_revision: Union[str, Sequence[str], None] = 'a9d672dcd0f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_attendance_student_date', 'attendance', ['student_id', 'date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_attendance_student_date', 'attendance', type_='unique')
    # ### end Alembic commands ###
