"""add class relationship to students

Revision ID: 7e10e594b42e
Revises: 31fb2fdda8ca
Create Date: 2026-09-07 15:16:07.811141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e10e594b42e'
down_revision: Union[str, Sequence[str], None] = '31fb2fdda8ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('class_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'students', 'classes', ['class_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_column('students', 'class_id')
    # ### end Alembic commands ###
