"""add unique constraint to marks

Revision ID: a0dc2187c245
Revises: 23df51d79f6a
Create Date: 2026-09-07 20:16:49.716262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0dc2187c245'
down_revision: Union[str, Sequence[str], None] = '23df51d79f6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_mark_student_exam_subject', 'marks', ['student_id', 'exam_id', 'subject_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_mark_student_exam_subject', 'marks', type_='unique')
    # ### end Alembic commands ###
