"""add fee structure linkage to fees

Revision ID: c15631020caf
Revises: 3beedc393323
Create Date: 2026-09-09 15:07:45.392649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c15631020caf'
down_revision: Union[str, Sequence[str], None] = '3beedc393323'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fees', sa.Column('fee_structure_id', sa.Integer(), nullable=True))
    op.add_column('fees', sa.Column('academic_session_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_fees_academic_session_id'), 'fees', ['academic_session_id'], unique=False)
    op.create_index(op.f('ix_fees_fee_structure_id'), 'fees', ['fee_structure_id'], unique=False)
    op.create_foreign_key(None, 'fees', 'academic_sessions', ['academic_session_id'], ['id'])
    op.create_foreign_key(None, 'fees', 'fee_structures', ['fee_structure_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fees', type_='foreignkey')
    op.drop_constraint(None, 'fees', type_='foreignkey')
    op.drop_index(op.f('ix_fees_fee_structure_id'), table_name='fees')
    op.drop_index(op.f('ix_fees_academic_session_id'), table_name='fees')
    op.drop_column('fees', 'academic_session_id')
    op.drop_column('fees', 'fee_structure_id')
    # ### end Alembic commands ###
